### ISSUE TITLE
我是技嘉B365M  安装时候卡PCI CONFIGURATION BEGIN？

### ISSUE THREAD

**Issue by a751116023** [liangzhenduo0608/hackintosh-efi#10]
我是技嘉B365M  安装时候卡PCI CONFIGURATION BEGIN？

**Comment by liangzhenduo0608** [comment]
试试这个 [https://github.com/dortania/OpenCore-Install-Guide/blob/master/troubleshooting/extended/kernel-issues.md#booter-issues](url)

**Comment by a751116023** [comment]
> 试试这个 [https://github.com/dortania/OpenCore-Install-Guide/blob/master/troubleshooting/extended/kernel-issues.md#booter-issues](url)

这个地址打开是空的？

**Comment by liangzhenduo0608** [comment]
https://github.com/dortania/OpenCore-Install-Guide/blob/master/troubleshooting/extended/kernel-issues.md#uefi-issues
插链接忘了插内容

**Comment by liangzhenduo0608** [comment]
> > 试试这个 [https://github.com/dortania/OpenCore-Install-Guide/blob/master/troubleshooting/extended/kernel-issues.md#booter-issues](url)
> 
> 这个地址打开是空的？

https://github.com/dortania/OpenCore-Install-Guide/blob/master/troubleshooting/extended/kernel-issues.md#stuck-on-rtc-pci-configuration-begins-previous-shutdown-hpet-hid-legacy

**Comment by liangzhenduo0608** [comment]
Since you haven't replied for more than a year, I've closed this issue.
