### ISSUE TITLE
用了你的EFI，很完美

### ISSUE THREAD

**Issue by wangweitung** [liangzhenduo0608/hackintosh-efi#15]
大佬，用了你的EFI，很完美。

唯一问题是ipad air的随航没法使用。

**Comment by liangzhenduo0608** [comment]
> 大佬，用了你的EFI，很完美。
> 
> 唯一问题是ipad air的随航没法使用。

手里没有iPad设备所以没测试过；理论上网卡应该是支持的，会和核显有关吗

**Comment by liangzhenduo0608** [comment]
确认没有核显无法随航
