### ISSUE TITLE
安装跑完进度条就黑屏了 是咋回事

### ISSUE THREAD

**Issue by Jonathan143** [liangzhenduo0608/hackintosh-efi#17]
同主板 cpu  显卡6600xt  安装跑完进度条就黑屏了 是咋回事

**Comment by liangzhenduo0608** [comment]
看看是不是驱动或补丁没打好，加-v看看日志
https://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1920667

**Comment by Jonathan143** [comment]
已解决  boot-args 启动项添加 `agdpmod=pikera` 就行了
