### ISSUE TITLE
可以提供一下镜像地址吗？

### ISSUE THREAD

**Issue by qinf** [liangzhenduo0608/hackintosh-efi#19]
我看网上都是12.6 ios镜像，暂时没找到dmg镜像，ios镜像写入u盘无法写个EFI文件。希望提供帮提供一下12.6的dmg镜像地址

**Comment by liangzhenduo0608** [comment]
试试这个工具 [https://github.com/corpnewt/gibMacOS](https://github.com/corpnewt/gibMacOS)

**Comment by liangzhenduo0608** [comment]
基本没什么问题，已知的就是iPad随航能连上但是黑屏，可能有的usb口需要定制，别的就没有感知到了
