### ISSUE TITLE
您10.5用了挺久了，日常感受咋样？小瑕疵有哪些啊？

### ISSUE THREAD

**Issue by c1awn** [liangzhenduo0608/hackintosh-efi#2]

**Comment by liangzhenduo0608** [comment]
我主要用的是无线网卡，日常无线速率580Mbps，有线连接没测试过
蓝牙使用正常，可以连接蓝牙音箱，但是传输文件没测试过
显卡免驱，显示器用的2k分辨率，但是有时屏幕最底下会出一条绿线，感觉是显示向上偏移了一个像素，有时正常，感觉无伤大雅
其他没什么问题
