### ISSUE TITLE
请问主板一样，但是使用的是核显需要修改什么吗

### ISSUE THREAD

**Issue by viajes7** [liangzhenduo0608/hackintosh-efi#5]
CPU是i5-9400，带核显UHD630，目前没有配置独立显卡。
请问EFI可以直接用不，需不需要做什么修改？

**Comment by liangzhenduo0608** [comment]
> CPU是i5-9400，带核显UHD630，目前没有配置独立显卡。
> 请问EFI可以直接用不，需不需要做什么修改？

好像有些不同 参考 https://github.com/daliansky/daliansky.github.io/issues/132

**Comment by viajes7** [comment]
好的，感谢

**Comment by viajes7** [comment]
昨天已经安装成功了，谢谢分享

现在又一个问题，就是开机、关机的时候在跑代码。clover configurator读取config.plist文件的时候，发现boot arguments里面又没有-v选项，只有一个slide=0。
开机的时候，通过clover节目查看options，boot arguments还是有很多参数的，其中包括了-v

感觉是clover configurator的兼容性问题吗？你目前使用的是哪个版本的clover configurator呢？

**Comment by liangzhenduo0608** [comment]
我用的5.14.0.0，开关机没出现verbose的情况

**Comment by viajes7** [comment]
找到了，是NVRAM里面，kernel boot args: -v brcmfx-aspm -lilubetaall alcid=1 brcmfx-driver=0
用的黑果小兵的镜像，脑壳疼，我再看下咋弄

**Comment by viajes7** [comment]
通过恢复模式，清空nvram成功了，谢谢分享efi
