### ISSUE TITLE
你好大佬

### ISSUE THREAD

**Issue by tumason** [liangzhenduo0608/hackintosh-efi#7]
我的CPU是i5-8500 带核显uhd630，其他配置都一样，请问双显要怎么设置硬解

**Comment by tumason** [comment]
不知道设置硬解FCPX加速能帮帮我么

**Comment by liangzhenduo0608** [comment]
> 我的CPU是i5-8500 带核显uhd630，其他配置都一样，请问双显要怎么设置硬解

https://zhuanlan.zhihu.com/p/93657416  这个是不是你要的

**Comment by tumason** [comment]
嗯是的COLOVER到是会OC不知如何操作

**Comment by liangzhenduo0608** [comment]
https://www.reddit.com/r/hackintosh/comments/gx6533/intel_uhd_360_graphics_not_accelerate/
https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html

**Comment by tumason** [comment]
> https://www.reddit.com/r/hackintosh/comments/gx6533/intel_uhd_360_graphics_not_accelerate/
> https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html

谢谢了我去学习下
